language: php
php:
- 5.4
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  global:
    secure: bymzsWZkONVMfzTNkatV3ID4tGipDxkjnY/la2Y0+GuvM0dunV6KslWnowaJmGTkqbbESpOPAmceoAheL4OnnB3EPA94uE3SD45NJaKy7U3Bx5TA/XAmB2APb5pG/lVM2ExNGOcFVpBTMYFhXd6t30UHV7ym9q1jszyFSfMhmD0=
    secure: pgXZQ6FdnGayxBzTbtEpsHHyeZE+R3so5Uh2VioBb3fcOw56+yntndJpnOIByR9/PX7ehigdCtCGyCzFM0k4TL7ld7MTZJb0SCttt6Md1c7PjyI6dyR4pAm8Y7+0kDbbX4tfnBa7OGDQLRh0mh6l6au97Q5PYQ4b+Ggp46mULU0=
